export const FETCH_USER_REQUEST = "user.get.state.request"
export const FETCH_USER_SUCCESS = "user.get.state.success"
export const FETCH_USER_FAILURE = "user.get.state.error"
export const FETCH_USER_CANCEL = "user.get.state.cancel"
export const FETCH_USER_STATE = "user.get.state"
export const SET_USER = "user.set"
export const SET_NAME = "user.set.name"
export const SET_ROOM = "user.set.room"
